server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/hr
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: spring123

logging:
  level:
    org.springframework.jdbc.core: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.sql: debug
    org.springframework.jdbc: DEBUG